### PR TITLE
bug(refs DPLAN-12445): Improve accessibility

### PR DESCRIPTION
**Pull request by gruenbergerdemos**
### Ticket
DPLAN-12445

Make focus with keyboard more clear. 
- Add keyboard focus on editor toolbar items
- Add 50% opacity for box shadow on focused buttons (recommended by ui/uix team)

### How to review/test
Öffentlichkeitsansicht Verfahren -> Reden Sie mit -> focus with keyboard and see if everything has visible outline

### CODE REVIEW

**Review by spiess-demos — COMMENTED** [review]
Why do you use outline here, and change the box-shadow opacity of the scss mixin "keyboard-focus"?

**Review by spiess-demos — APPROVED** [review]
lgtm!

**Review by hwiem — CHANGES_REQUESTED** [review]
The flyout button is entirely skipped with the keyboard, isn't it?  <- Edit: I realized there is a separate bug ticket for that and I now saw your comment in the ticket, so nevermind this.

And the Diplanung/Home link focus style looks different from the navigation links' one - if it's not too complicated, I think we should make it consistent.

Apart from that I think it's very nice. :tada: 

I also noticed that the "Markieren" button in the tiptap editor is not aligned properly, should we fix it here also or should we create a new ticket?

**Comment by gruenbergerdemos** [comment]
> And the Diplanung/Home link focus style looks different from the navigation links' one - if it's not too complicated, I think we should make it consistent.

I changed it in the linked project PRs. 

> I also noticed that the "Markieren" button in the tiptap editor is not aligned properly, should we fix it here also or should we create a new ticket?

I think we need to fix that in demosplan-ui, so I think we should make a new ticket.

**Review by hwiem — APPROVED** [review]
lgtm!

**Pull request merged**
