### PR TITLE
fix (refs DPLAN-12508): fix wrong customer in url

### PR DESCRIPTION
**Pull request by breierDemos**
### Ticket
[DPLAN-12508](https://demoseurope.youtrack.cloud/issue/DPLAN-12508/Mandanten-spezifische-Weiterleitung-funktioniert-nicht)

The URL also has to be adjusted in the SubdomainHandler because the value of externalLinks in GlobalConfig can be used before being adjusted during the SubdomainHandler.

### How to review/test
code review

### PR Checklist

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

### CODE REVIEW

**Comment by sierrazamudiodemos** [comment]
I think this is more to merge in master as diplanbau is already release right?

**Review by mussbach — CHANGES_REQUESTED** [review]
Looks correct, but I think you can remove the logic in GlobalConfig:822 ff. now

**Comment by breierDemos** [comment]
@mussbach adjusted in [331ed5c](https://github.com/demos-europe/demosplan-core/pull/3732/commits/331ed5c14451639959ebd0f8b69a4f64319ab84c)
I changed the target branch to main.

**Review by mussbach — APPROVED** [review]
lgtm, code review only, thx

**Pull request merged**
