### PR TITLE
refacor: Create api2.0 Routes Dynamically

### PR DESCRIPTION
**Pull request by salisdemos**
With That, we don't have to register the routes manually in the VuexApiRoutes.js. Now they get build during the store initialization depending on the entrypoint

### CODE REVIEW

**Review by spiess-demos — APPROVED** [review]
nice improvement! lgtm (code review)

**Comment by mussbach** [comment]
@salisdemos could this me merged?

**Comment by salisdemos** [comment]
> @salisdemos could this me merged?

Its a stacked PR points to an PR that should be reviewed first. To not confuse.

**Comment by salisdemos** [comment]
to merge the content early I created a new PR that points to main: https://github.com/demos-europe/demosplan-core/pull/3285

**Pull request closed without merging**
