### PR TITLE
Update Release_bobhh

### PR DESCRIPTION
**Pull request by jalalifardemos**
All of this Changes be merged in main by https://github.com/demos-europe/demosplan-core/pull/3534, but we need this things for release_bobhh and cockpit

### CODE REVIEW

**Comment by mussbach** [comment]
@jalalifardemos did you cherry-pick the changes or did you reimplement them?

**Comment by jalalifardemos** [comment]
Just reimplement

**Comment by mussbach** [comment]
A cherry-pick would be better if possible to avoid merge issues. What commits need to be included?

**Comment by jalalifardemos** [comment]
I don't know how is Cherry-pick, sorry

**Comment by mussbach** [comment]
I can do it, which commits needs to be included?

**Comment by jalalifardemos** [comment]
I think is 332eeb8d81f111c1b42658d876590fca4d533533

**Pull request closed without merging**
