### PR TITLE
feat (refs T33577): bring dplan-core into line with demosplan-addon changes

### PR DESCRIPTION
**Pull request by martendemos**
**Ticket:** https://yaits.demos-deutschland.de/

Simple adjustment to a renaming in dplan-addon.

#### depends on :arrow_up::
- https://github.com/demos-europe/demosplan-core/pull/2379

#### is depending on this one :arrow_down::
- https://github.com/demos-europe/demosplan-addon/pull/79
- https://github.com/demos-europe/demosplan-addon/pull/81
- https://github.com/demos-europe/demosplan-core/pull/2269/

### PR Checklist
- [x] Tests updated/created
- [x] Link all relevant tickets
- [ ] Move the tickets on the board accordingly

### CODE REVIEW

**Review by breierDemos — CHANGES_REQUESTED** [review]
3 more adjustments needed in ElementsServiceTest.php
line 653, 654 and 655

**Comment by martendemos** [comment]
> 3 more adjustments needed in ElementsServiceTest.php line 653, 654 and 655

https://github.com/demos-europe/demosplan-core/pull/2331/commits/2c5e89895e030bdb119ccc26d292c87fcf29c67f

**Review by breierDemos — DISMISSED** [review]

**Comment by martendemos** [comment]
To get rid of the review dog reports, https://github.com/demos-europe/demosplan-addon/pull/81 needs to be merged and the composer lockfile needs to be updated.

**Comment by martendemos** [comment]
related new version of demosplanaddon: https://github.com/demos-europe/demosplan-addon/pull/81

**Review by jalalifardemos — APPROVED** [review]
Thx, Code review only

**Pull request merged**
