### PR TITLE
feat(refs DPLAN-11888): Pass Number instead of null

### PR DESCRIPTION
**Pull request by salisdemos**
DPLAN-11888

- Add fallback to pager. null is not allowed anymore.
- Add missing Api-1.0 Routes (Just to be sure)

### CODE REVIEW

**Review by hwiem — COMMENTED** [review]
Should the api route changes be in this PR?

**Comment by salisdemos** [comment]
> Should the api route changes be in this PR?

got me. I was lazy. I thought its small enough to fit in the same PR

**Comment by hwiem** [comment]
> > Should the api route changes be in this PR?
> 
> got me. I was lazy. I thought its small enough to fit in the same PR

I don't even mind that :sweat_smile: but I think it should be included in the PR description (in the future)

**Review by hwiem — APPROVED** [review]
lgtm, code review only

**Comment by salisdemos** [comment]
> > > Should the api route changes be in this PR?
> > 
> > 
> > got me. I was lazy. I thought its small enough to fit in the same PR
> 
> I don't even mind that 😅 but I think it should be included in the PR description (in the future)

Actually it is in the description, but not in the title

**Comment by hwiem** [comment]
> > > > Should the api route changes be in this PR?
> > > 
> > > 
> > > got me. I was lazy. I thought its small enough to fit in the same PR
> > 
> > 
> > I don't even mind that 😅 but I think it should be included in the PR description (in the future)
> 
> Actually it is in the description, but not in the title

:D in that case, note to self: read the description

**Pull request merged**
