### PR TITLE
bug(refs DPLAN-11421): Add readon link for news

### PR DESCRIPTION
**Pull request by gruenbergerdemos**
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11421

Add a readon link for the news' full text.

### CODE REVIEW

**Review by sakutademos — COMMENTED** [review]
Is it intended that other bug fixes are included in this PR?

**Comment by sierrazamudiodemos** [comment]
> Is it intended that other bug fixes are included in this PR?

Hey @sakutademos the fix done by Alex is already merged in the release branch. That said, we can safely merge this pr :) Thanks for keeping an eye ;)

**Review by bakridemos — APPROVED** [review]

**Review by spiess-demos — APPROVED** [review]
frontend looks good to me (code review only).

**Review by sakutademos — APPROVED** [review]
lgtm

**Pull request merged**
