### PR TITLE
f T36701 Sorting by input number proceduces an error

### PR DESCRIPTION
**Pull request by bakridemos**
**Ticket:** https://yaits.demos-deutschland.de/T36701

Description: the internId has to be sortable to make sorting work.

### How to review/test

Start > Procedure of your organization > Select procedure > statements list > Sorting: Input number ascending/Input number descending

Delete the checkbox if it doesn't apply/isn't necessary.

- [X] Tests updated/created
- [X] Update documentation

### CODE REVIEW

**Comment by bakridemos** [comment]
i had to adjust it one more time hier https://github.com/demos-europe/demosplan-core/pull/2886/commits/c2f143ff4c3f898a787b5c5a1ab491856e62b33f

**Review by dresslerdemos — CHANGES_REQUESTED** [review]
This will work, but the property is already set as readable in the parent class, so there is no reason to repeat it here. Also setting it sortable may not be the best approach, instead we may want to merge https://github.com/demos-europe/demosplan-core/pull/2574

**Comment by bakridemos** [comment]
this pr will be closed, it should be fixed with https://github.com/demos-europe/demosplan-core/pull/2574

**Comment by bakridemos** [comment]
this pr will be closed, it should be fixed with https://github.com/demos-europe/demosplan-core/pull/2574

**Comment by bakridemos** [comment]
this pr will be closed, it should be fixed with https://github.com/demos-europe/demosplan-core/pull/2574

**Pull request closed without merging**
