### PR TITLE
feature (refs T33554): fix procedure export

### PR DESCRIPTION
**Pull request by jalalifardemos**
**Ticket:** https://yaits.demos-deutschland.de/T33554

Description: ZipExportService should return void, but return int.

### How to review/test
just check it in browser

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly

### CODE REVIEW

**Review by MoritzMandler — APPROVED** [review]
lgtm - tested and works fine

**Review by mussbach — CHANGES_REQUESTED** [review]
shouldn't this be based on release?

**Comment by jalalifardemos** [comment]
I don't know, should be Release?

**Comment by AlexMenschoid** [comment]
Something is strange here, there are too many changes in this PR and too many commits that don't sound like they belong here. Could it be that this was branched off `release_diplanbau` for some reason?

**Comment by jalalifardemos** [comment]
Yes, I changed just ZipExportService, I don't know these changes come from where

**Comment by jalalifardemos** [comment]
Close because of wrong base branch.
replace with https://github.com/demos-europe/demosplan-core/pull/1639

**Pull request closed without merging**
