### PR TITLE
chore (refs T33553): adjust Trans-Key, useSaml for register user.

### PR DESCRIPTION
**Pull request by ahmad-demos**
https://yaits.demos-deutschland.de/T33553

- adjust useSaml for register user.

### CODE REVIEW

**Review by mussbach — APPROVED** [review]
lgtm, thx

**Comment by spiess-demos** [comment]
@ahmad-demos when searching for `Nutzerkonto Brandenburg`, there are still plenty of occurrences. Do we need to keep those in the code?

**Comment by ahmad-demos** [comment]
> @ahmad-demos when searching for `Nutzerkonto Brandenburg`, there are still plenty of occurrences. Do we need to keep those in the code?

We have only `register.saml.citizen.description ` in blp/messages+intl-icu.de.yml
but another keys in core.
do I have to delete everything?

@mussbach cc

**Comment by spiess-demos** [comment]
> We have only `register.saml.citizen.description ` in blp/messages+intl-icu.de.yml but another keys in core. do I have to delete everything?

I'd suggest to look into each occurrence, where it is used, and decide if it can be removed, too. As i understand it, the entire "Nutzerkonto Brandenburg" service will be discontinued on October 31st, so we could remove all code related to it. However this must be made cleanly (from a frontend perspective, also take into account the markup in Twig and Vue
 files, where the translation files are used, and from a backend perspective, also remove permissions, and "other backendy stuff like routes, actions, controllers etc".

**Comment by ahmad-demos** [comment]
> > We have only `register.saml.citizen.description ` in blp/messages+intl-icu.de.yml but another keys in core. do I have to delete everything?
> 
> I'd suggest to look into each occurrence, where it is used, and decide if it can be removed, too. As i understand it, the entire "Nutzerkonto Brandenburg" service will be discontinued on October 31st, so we could remove all code related to it. However this must be made cleanly (from a frontend perspective, also take into account the markup in Twig and Vue files, where the translation files are used, and from a backend perspective, also remove permissions, and "other backendy stuff like routes, actions, controllers etc".

- `register.saml.citizen.description` in `blp/messages+intl-icu.de.yml` used in `CitizenRegisterForm.vue`
- `login.other_account` in `dplan/translations/messages+intl-icu.de.yml` used in `CitizenRegisterForm.vue, OrgaRegisterForm.vue & SamlLoginForm.vue`
- login.other_account: "Mit Nutzerkonto Brandenburg anmelden" in `dplan/translations/messages+intl-icu.de.yml`, aber in `blp/messages+intl-icu.de.yml`: `login.other_account: "Mit anderem Konto anmelden"`
- `login.saml.description` in `dplan/translations/messages+intl-icu.de.yml` used in `SamlLoginForm.vue`
- `register.saml` in `dplan/translations/messages+intl-icu.de.yml` used in `CitizenRegisterForm.vue`

**Comment by mussbach** [comment]
Nutzerkonto Brandenburg is discontinued but will be replaced by BundID. I think we should support it soon and therefore I would not remove the entire logic for Nutzerkonto Brandenburg as we can reuse it mostly 1:1 and just rename it

**Pull request merged**
