### PR TITLE
chore: Run yarn upgrade

### PR DESCRIPTION
**Pull request by salisdemos**
Upgrade outdated subdependencies our dependencies by running `yarn upgrade`

### CODE REVIEW

**Review by hwiem — COMMENTED** [review]
I get this error
`Module not found: Error: Can't resolve 'olcs/lib/olcs/VectorSynchronizer.js' in '/srv/www/node_modules/@masterportal/masterportalapi/src/maps/olcs'`
but maybe that's a local problem?

**Comment by salisdemos** [comment]
> I get this error `Module not found: Error: Can't resolve 'olcs/lib/olcs/VectorSynchronizer.js' in '/srv/www/node_modules/@masterportal/masterportalapi/src/maps/olcs'` but maybe that's a local problem?

:thinking: not good. I think, then we have to find another constellation.

**Comment by salisdemos** [comment]
@hwiem maybe that one works? https://github.com/demos-europe/demosplan-core/pull/3203
Then I would close this one here.

**Comment by hwiem** [comment]
> @hwiem maybe that one works? #3203 Then I would close this one here.

I get the same error both on that branch and on `main`. I think it might be unrelated to your changes, but maybe someone else could check.

**Comment by salisdemos** [comment]
closed in favor of https://github.com/demos-europe/demosplan-core/pull/3203

**Pull request closed without merging**
