### PR TITLE
chore: use MessageBagInterface in DI to show all messages

### PR DESCRIPTION
**Pull request by mussbach**
MessageBagInterface should be used in DI everywhere, as otherwise another instance of the MessageBag is instantiated and the collected messages are never shown in the interface

### PR Checklist

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [ ] Link all relevant tickets
- [ ] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

### CODE REVIEW

**Review by sierrazamudiodemos — CHANGES_REQUESTED** [review]
Double message when creating an stn

- I create a stn im ewm (Direkt stn)
- Double success message is displayed.
- It does not happen in dev

**Comment by mussbach** [comment]
> Double message when creating an stn
> 
>     * I create a stn im ewm (Direkt stn)
> 
>     * Double success message is displayed.
> 
>     * It does not happen in dev

yes, most likely we will have duplicated notifications now. The new messages where introduced to fix this bug, but did not fix the root cause. Not sure how to handle this as wit this PR are quite likely a bunch of messages fixed that where not even found as bugs. Do you think we should find any duplicated messages beforehand @sierrazamudiodemos ?

**Comment by sierrazamudiodemos** [comment]
> > Double message when creating an stn
> > ```
> > * I create a stn im ewm (Direkt stn)
> > 
> > * Double success message is displayed.
> > 
> > * It does not happen in dev
> > ```
> 
> yes, most likely we will have duplicated notifications now. The new messages where introduced to fix this bug, but did not fix the root cause. Not sure how to handle this as wit this PR are quite likely a bunch of messages fixed that where not even found as bugs. Do you think we should find any duplicated messages beforehand @sierrazamudiodemos ?

How can we find newly created messages? or is there a way that maybe you have on top of your mind to find duplicated messages?

**Comment by sierrazamudiodemos** [comment]
> Do you think we should find any duplicated messages beforehand @sierrazamudiodemos 

I tend towards a yer because I want to avoid qa labeling as a blocker or red bug, or introducing a differnent behaviour. On other hand it is good to let people know that we should use MessageInterface

when commenting from line 2920 to line 2927 in demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php then only one notification is displayed.

I wonder if looking for $this->getMessageBag()->addObject and testing the functionality there will remove the duplicated notifications.

**Comment by mussbach** [comment]
These are more or less exactly my thoughts about this :-) We could also as a supporting measure briefly check the recent git history of all the files that are within this PR and scan the commit messages for occurrences of "message" "notification" or the like

**Comment by sierrazamudiodemos** [comment]
Oki I understand. I will approve it and I think we could merge in main, so we have the following sprints to fix it, what do you think? the idea of the commits history is good

**Review by sierrazamudiodemos — APPROVED** [review]

**Comment by sierrazamudiodemos** [comment]
Thanks for the discussion :-)

**Pull request merged**
