### PR TITLE
Feat(refs:35155): add the new greeting formel

### PR DESCRIPTION
**Pull request by elmasdemos**
**Ticket:** https://yaits.demos-deutschland.de/T35155

Description: 

- replace the old greeting form with the new one

### PR Checklist

- [x] Tests updated/created
- [x] Update documentation

### CODE REVIEW

**Review by hwiem — COMMENTED** [review]
Should this be changed in all of these templates?

**Review by muellerdemos — CHANGES_REQUESTED** [review]
These changes shall be committed to the core templates? The tickets reads it is only for diplanrog, or am I mistaken here?

**Comment by elmasdemos** [comment]
> Should this be changed in all of these templates?

yes, but i can do it another PR, but than it doesnt have a ticket. it says in the main ticket, that this should have been changed in core

**Comment by elmasdemos** [comment]
> These changes shall be committed to the core templates? The ticket https://yaits.demos-deutschland.de/T33939 reads it is only for diplanrog, or am I mistaken here?

when you look into the main ticket, it says it shall be changed in the core. I wrote with @po but if desired I cfan do another PR without any reference or ask for a new ticket

**Comment by elmasdemos** [comment]
anyway, my idea was to make the work later easier, but i reverted the changes and just changed only the one place

**Comment by hwiem** [comment]
> anyway, my idea was to make the work later easier, but i reverted the changes and just changed only the one place

I think it was fine to include the other templates, I just didn't find the info that they need to be changed, hence my question

**Review by muellerdemos — APPROVED** [review]
I did not meant to remove the changes if they are needed, I just saw in the ticket the checkbox for a single project and wanted to be sure this is correct. However this lgtm - sorry for the hassle

**Review by hwiem — APPROVED** [review]

**Pull request merged**
